### ISSUE TITLE
In debug, there is an exception during tests because 1 234,00 is returned when 1,234.00 is expected

### ISSUE THREAD

**Issue by ABSTRACT123** [Bernardo-Castilho/CalcEngine#1]
Hello,

Thank you for this library. I'm starting a few tests. So I included calcEngine project into my test solution but I have an exception message when I instantiate the calcEngine which is due to the tests being performed.

I don't know if it has an impact anywhere else anyway I thought it was worth mentioning. 
My system is configured in french so In debug, there is an exception during tests because 1 234,00 is returned when 1,234.00 is expected.

Thank you

**Comment by Bernardo-Castilho** [comment]
Thanks for reporting this.

The problem is in this line of the test method:

            ce.Test("TEXT(1234, \"n2\")", "1,234.00"); // not localizable

It should be this to support globalization:

            ce.Test("TEXT(1234, \"n2\")", (1234).ToString("n2")); // localizable

I have fixed this in the Text.cs file, thanks again for reporting the problem.
