### ISSUE TITLE
Run CalcEngine in SQL Server

### ISSUE THREAD

**Issue by vlad-kaplan** [Bernardo-Castilho/CalcEngine#12]
First thank you very much for this library and the article. And thank you for opening it for everybody, I appreciate it.
I tried to run it as a CLR Component in SQL Server. (That would allow me to calculate formula directly in SQL-Queries). In order to register this library in SQL Server with permission set "safe", I had to mark static variables as readonly in two places:
- MathTrig.cs, Row 216: "static **readonly** Random _rnd = new Random();
- Expression.cs, Row 27: static **readonly** CultureInfo _ci = CultureInfo.InvariantCulture;

If you could adopt those changes, that would allow to use your library as a "safe" under SQL Server without manual changes.

**Comment by Bernardo-Castilho** [comment]
Hi Vlad

Thanks very much for the comments and suggestions.

I have applied the changes as you suggested.

**Comment by vlad-kaplan** [comment]
Thanks for applying and letting me know.

Vlad.

сб, 23 сент. 2023 г. в 16:16, Bernardo Castilho ***@***.***>:
