### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ABSTRACT123** [Bernardo-Castilho/CalcEngine#2]
Hello Bernardo,

Thank you for your quick answer. I'm trying to replace another lib with yours in my project but I'm struggling with minor issues. For instance this if(5>0,3,2)  returns 3  but I get a syntax error with this if(5>0 and 5>2,3,2). I tried using & also.

Also how can I have variables with white spaces. If I use [x y] I get an exception, same if I try "x y".

I guess these are not issues but improper use that's why I was wondering if there was any documentation that could help me.

If you ever come to release a new version in the future, may I suggest the use of a constants file for the function names and error messages to help with the localization issues. 

Thanks a lot for your time and effort as your library is really helping.

Regards
Amar

**Comment by Stumpii** [comment]
In Excel, you would have to write =IF(AND(5>0, 5>2),3,2) . This appears to work fine.

Steve

**Comment by ABSTRACT123** [comment]
Ok thank you Steve. I was suspecting something like that.. I don't have Excel :p

If all I have to do is search for the Excel documentation, it's ok for me. Meanwhile, I moved forward and I'm starting to be more and more comfortable with calcEngine.

Thank you very much.

Amar

edit: If you could tell me why it generates an exception if I write something like 1+$x or 1+[x] or 1+"x", it doesn't call the GetExternalObject function. I'm trying to have a way to differentiate between variables (for instance quantity) that the user enters and fields (for instance price of product x) that I get from the db. Thank you

**Comment by Stumpii** [comment]
Do a google search for 'AND excel function' will show many examples. Or take a peak at the source [Logical](https://github.com/Bernardo-Castilho/CalcEngine/blob/master/Source/CalcEngine/CalcEngine/Functions/Logical.cs) for examples. I found this the easiest way to find out the supported functions.

As for 'x', have you tried using the Variable Dictionary in the Variables example. I have not used it, but it looks like what you need:

`

            var ce = new CalcEngine.CalcEngine();
            var dct = new CalcDictionary(ce);
            ce.Variables = dct;
            
            dct["Amount"] = 12;
            dct["OfferPrice"] = 12.32;
            dct["Item1"] = "=Amount * OfferPrice";
            dct["Item2"] = "=Item1 * 0.06";

            // this will print "8.8704" 
            // (Amount * OfferPrice) * 0.06 = 12 * 12.32 * 0.06 = 8.8704
            Console.WriteLine(ce.Evaluate("Item2"));
`

Where you would specify x:

`

            dct["x"] = 12;
            Console.WriteLine(ce.Evaluate("1 + x"));
`

**Comment by ABSTRACT123** [comment]
Hi Steve,

Thanks for your answer.

Actually the "x stuff" wasn't about the x by itself but about the character that would come before it like $ or around it like "" or [] it seems they are not accepted. And I was wondering why. I understand that the double quotes are used to identify strings but what about [] and $?

Yes you are right, the sources are of good help. Meanwhile I looked there and saw that it was also very easy to translate the functions names if needed.

Thank you for your help. As my points were answered ( I was a bit in a hurry and was not sure of my ability to integrate calcEngine into my project quickly but it is actually very efficient and easy to use) and this was not really an issue, I'm going to close it.

Thanks again.
