### ISSUE TITLE
Truncate returns wrong value when double.NaN is passed in

### ISSUE THREAD

**Issue by Cacowned** [Bernardo-Castilho/CalcEngine#3]
Use Math.Truncate() instead of the casting (double)(int)((double)p[0]);

**Comment by Bernardo-Castilho** [comment]
Fixed, thanks a lot for the heads-up!

**Comment by Cacowned** [comment]
Thanks for the quick response, however you've updated the "INT" function, but not the "TRUNC". I actually missed the error in the "INT" :)

**Comment by Bernardo-Castilho** [comment]
Oops... Sorry, fixed again. Thanks!
