### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tiesont** [Bernardo-Castilho/CalcEngine#4]
I see that the original Code Project article for this project lists the [COPL](https://www.codeproject.com/info/cpol10.aspx) as the license under this code is released; is that still in effect? If not, is it possible to specify a license in this GitHub project (the MIT license seems the closest, but obviously that's your call).

**Comment by Bernardo-Castilho** [comment]
Hello. I just changed the license on CodeProject to "public domain", which I guess has to be the most flexible of all. I also added a an MIT LICENSE.TXT file to the github version. Hope that takes care of things for you!

**Comment by tiesont** [comment]
Awesome. Thank you.
